// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gVLjp5jEanpB9JmP1wfhu5
// Component: _KYDKTjdvI
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: OiEpCGxwidZ/component
import Button2 from "antd/lib/button"; // plasmic-import: kv6Mk_JNYw/codeComponent
import Input from "antd/lib/input"; // plasmic-import: tO9wrxr8Nbb/codeComponent
import TextArea from "antd/lib/input/TextArea"; // plasmic-import: ZJIPHLoTjkN/codeComponent
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_zaviago_react_builder.module.css"; // plasmic-import: gVLjp5jEanpB9JmP1wfhu5/projectcss
import sty from "./PlasmicSettingPagePayment.module.css"; // plasmic-import: _KYDKTjdvI/css
import IconsvgIcon from "./icons/PlasmicIcon__Iconsvg"; // plasmic-import: ghfrvXPxoN/icon
import XmarksvgIcon from "./icons/PlasmicIcon__Xmarksvg"; // plasmic-import: 7zeOQd0aRb/icon
import framesvgQpMvVUojHj from "./images/framesvg.svg"; // plasmic-import: qpMvVUojHj/picture

export const PlasmicSettingPagePayment__VariantProps = new Array();

export const PlasmicSettingPagePayment__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicSettingPagePayment__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"creditDebitCard"}
            data-plasmic-override={overrides.creditDebitCard}
            className={classNames(projectcss.all, sty.creditDebitCard)}
          >
            <div className={classNames(projectcss.all, sty.column__n8Ff)}>
              <Button
                className={classNames("__wab_instance", sty.button__mfrCl)}
                color={"softSand"}
                endIcon={
                  <XmarksvgIcon
                    className={classNames(projectcss.all, sty.svg__g4Q87)}
                    role={"img"}
                  />
                }
                shape={"rounded"}
                showEndIcon={true}
                startIcon={
                  <IconsvgIcon
                    className={classNames(projectcss.all, sty.svg__mRzmo)}
                    role={"img"}
                  />
                }
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ptQgd
                  )}
                >
                  {"Edit"}
                </div>
              </Button>

              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                {"credit card / debit card ."}
              </h1>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__lgPWf
                )}
              >
                {
                  "Take payments in person via BACS. More commonly known as direct bank/wire transfer."
                }
              </div>
            </div>

            <div className={classNames(projectcss.all, sty.column__sJlkK)}>
              <p.Stack
                as={"div"}
                data-plasmic-name={"columns"}
                data-plasmic-override={overrides.columns}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns)}
              >
                <div className={classNames(projectcss.all, sty.column___8QzGs)}>
                  <Button2
                    className={classNames(
                      "__wab_instance",
                      sty.antdButton__siDm
                    )}
                    size={"medium"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__e20
                      )}
                    >
                      {"Back"}
                    </div>
                  </Button2>
                </div>

                <div className={classNames(projectcss.all, sty.column__cu1Ms)}>
                  <Button
                    className={classNames("__wab_instance", sty.button___2N1QC)}
                    showStartIcon={true}
                    startIcon={
                      <IconsvgIcon
                        className={classNames(projectcss.all, sty.svg___9Ek7)}
                        role={"img"}
                      />
                    }
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uTL
                      )}
                    >
                      {"Save Changes"}
                    </div>
                  </Button>
                </div>
              </p.Stack>
            </div>
          </div>

          <div
            data-plasmic-name={"information"}
            data-plasmic-override={overrides.information}
            className={classNames(projectcss.all, sty.information)}
          >
            <div className={classNames(projectcss.all, sty.column__oK5Yw)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__wbP4U
                )}
              >
                {"information"}
              </h2>

              <h3
                className={classNames(
                  projectcss.all,
                  projectcss.h3,
                  projectcss.__wab_text,
                  sty.h3___1N8Pf
                )}
              >
                {"This information showing to your user."}
              </h3>
            </div>
          </div>

          <div
            data-plasmic-name={"titleStatus"}
            data-plasmic-override={overrides.titleStatus}
            className={classNames(projectcss.all, sty.titleStatus)}
          >
            <div className={classNames(projectcss.all, sty.column__wJrC)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__fhSo2)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3___0XqtG
                  )}
                >
                  {"Title"}
                </h3>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__it5B1)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"12px"}
                  loading={"lazy"}
                  src={{
                    src: framesvgQpMvVUojHj,
                    fullWidth: 150,
                    fullHeight: 150,
                    aspectRatio: 1
                  }}
                />
              </p.Stack>

              <Input
                data-plasmic-name={"antdInput5"}
                data-plasmic-override={overrides.antdInput5}
                allowClear={false}
                aria-label={"Title"}
                bordered={true}
                className={classNames("__wab_instance", sty.antdInput5)}
                defaultValue={""}
                id={"Title"}
                name={"title"}
                placeholder={"Direct bank transfer"}
                size={"large"}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__igr3Y)}>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2___2Nt5L
                )}
              >
                {"status"}
              </h2>

              <Button2
                className={classNames("__wab_instance", sty.antdButton__rtkge)}
                danger={false}
                shape={"default"}
                size={"large"}
                type={"default"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___0Avr7
                  )}
                >
                  {"Enable"}
                </div>
              </Button2>
            </div>
          </div>

          <div
            data-plasmic-name={"description"}
            data-plasmic-override={overrides.description}
            className={classNames(projectcss.all, sty.description)}
          >
            <div className={classNames(projectcss.all, sty.column___7Vogx)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__eXf30)}
              >
                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__ls2F3
                  )}
                >
                  {"Description"}
                </h3>

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__j7Evo)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"12px"}
                  loading={"lazy"}
                  src={{
                    src: framesvgQpMvVUojHj,
                    fullWidth: 150,
                    fullHeight: 150,
                    aspectRatio: 1
                  }}
                />
              </p.Stack>

              <TextArea
                data-plasmic-name={"antdInputTextArea"}
                data-plasmic-override={overrides.antdInputTextArea}
                allowClear={false}
                aria-label={"Pay with cash upon delivery."}
                aria-labelledby={"Pay with cash upon delivery."}
                className={classNames("__wab_instance", sty.antdInputTextArea)}
                name={"paywithcod"}
                placeholder={
                  "Make your payment directly into our bank account. Please use your Order ID as the payment reference. Your order will not be shipped until the funds have cleared in our account."
                }
                showCount={false}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "creditDebitCard",
    "h1",
    "columns",
    "information",
    "titleStatus",
    "antdInput5",
    "description",
    "antdInputTextArea"
  ],

  creditDebitCard: ["creditDebitCard", "h1", "columns"],
  h1: ["h1"],
  columns: ["columns"],
  information: ["information"],
  titleStatus: ["titleStatus", "antdInput5"],
  antdInput5: ["antdInput5"],
  description: ["description", "antdInputTextArea"],
  antdInputTextArea: ["antdInputTextArea"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicSettingPagePayment__ArgProps,
          internalVariantPropNames: PlasmicSettingPagePayment__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicSettingPagePayment__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSettingPagePayment";
  } else {
    func.displayName = `PlasmicSettingPagePayment.${nodeName}`;
  }
  return func;
}

export const PlasmicSettingPagePayment = Object.assign(
  // Top-level PlasmicSettingPagePayment renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    creditDebitCard: makeNodeComponent("creditDebitCard"),
    h1: makeNodeComponent("h1"),
    columns: makeNodeComponent("columns"),
    information: makeNodeComponent("information"),
    titleStatus: makeNodeComponent("titleStatus"),
    antdInput5: makeNodeComponent("antdInput5"),
    description: makeNodeComponent("description"),
    antdInputTextArea: makeNodeComponent("antdInputTextArea"),
    // Metadata about props expected for PlasmicSettingPagePayment
    internalVariantProps: PlasmicSettingPagePayment__VariantProps,
    internalArgProps: PlasmicSettingPagePayment__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSettingPagePayment;
/* prettier-ignore-end */
